import { createThemeDefinition } from "./tokens.js";

export const appAnnouncementTheme = createThemeDefinition({
  "--color-scheme": "light",
  "--color-bg": "#f7f1e8",
  "--color-surface": "#ffffff",
  "--color-surface-alt": "#efe5d7",
  "--color-text": "#261c17",
  "--color-text-muted": "#67574c",
  "--color-border": "#d8ccb9",
  "--color-primary": "#a0542f",
  "--color-primary-contrast": "#fff8f1",
  "--color-accent": "#5f725c",
  "--color-link": "#8f4523",
  "--color-link-hover": "#6e3217",
  "--color-focus-ring": "#a9714f",
  "--page-background": "#f7f1e8",
  "--surface-background": "#ffffff",
  "--hero-background": "#fbf7f0",
  "--cta-background": "#f1e8db",
  "--font-family-body": "\"Gill Sans\", \"Avenir Next\", sans-serif",
  "--font-family-heading": "\"Gill Sans\", \"Avenir Next\", sans-serif",
  "--heading-letter-spacing": "-0.03em",
  "--font-size-5": "2.2rem",
  "--font-size-6": "3.1rem",
  "--line-height-heading": "1.03",
  "--button-letter-spacing": "0.015em",
  "--space-7": "2.75rem",
  "--space-8": "3.75rem",
  "--button-height": "2.875rem",
  "--radius-md": "0.5rem",
  "--radius-lg": "0.625rem",
  "--radius-xl": "0.75rem",
  "--shadow-sm": "0 3px 8px rgb(60 33 16 / 0.08)",
  "--shadow-md": "0 4px 12px rgb(60 33 16 / 0.1)",
  "--shadow-lg": "0 8px 24px rgb(60 33 16 / 0.14)",
  "--button-hover-transform": "none",
});
