import { createThemeDefinition } from "./tokens.js";

export const brutalismTheme = createThemeDefinition({
  "--color-scheme": "light",
  "--color-bg": "#fff7e8",
  "--color-surface": "#ffffff",
  "--color-surface-alt": "#ffe0a8",
  "--color-text": "#0b0b0b",
  "--color-text-muted": "#2d2d2d",
  "--color-border": "#0b0b0b",
  "--color-primary": "#ff4d00",
  "--color-primary-contrast": "#111111",
  "--color-accent": "#ffd400",
  "--color-link": "#111111",
  "--color-link-hover": "#ff4d00",
  "--color-focus-ring": "#ff4d00",
  "--page-background":
    "repeating-linear-gradient(135deg, #fff7e8 0 28px, #ffe0a8 28px 56px)",
  "--surface-background": "linear-gradient(180deg, #ffffff 0%, #fff2ca 100%)",
  "--hero-background": "linear-gradient(135deg, #ffffff 0%, #ffd400 100%)",
  "--cta-background": "linear-gradient(135deg, #ff4d00 0%, #ffd400 100%)",
  "--font-family-body": "Verdana, Geneva, sans-serif",
  "--font-family-heading": "\"Arial Black\", Impact, sans-serif",
  "--heading-letter-spacing": "0.03em",
  "--font-size-4": "1.875rem",
  "--font-size-5": "2.4rem",
  "--font-size-6": "3.8rem",
  "--line-height-heading": "0.9",
  "--font-weight-bold": "900",
  "--button-letter-spacing": "0.08em",
  "--button-height": "3rem",
  "--radius-sm": "0",
  "--radius-md": "0",
  "--radius-lg": "0",
  "--radius-xl": "0",
  "--border-width-2": "3px",
  "--border-width-3": "4px",
  "--shadow-sm": "4px 4px 0 rgb(0 0 0 / 1)",
  "--shadow-md": "8px 8px 0 rgb(0 0 0 / 1)",
  "--shadow-lg": "12px 12px 0 rgb(0 0 0 / 1)",
  "--button-hover-transform": "translate(-3px, -3px)",
});
