import { createThemeDefinition } from "./tokens.js";

export const brutalismTheme = createThemeDefinition({
  "--color-scheme": "light",
  "--color-bg": "#efe0bd",
  "--color-surface": "#fff8ea",
  "--color-surface-alt": "#e6c992",
  "--color-text": "#0b0b0b",
  "--color-text-muted": "#2d2d2d",
  "--color-border": "#0b0b0b",
  "--color-primary": "#a14621",
  "--color-primary-contrast": "#fff8ea",
  "--color-accent": "#7c6b2e",
  "--color-link": "#111111",
  "--color-link-hover": "#8b3417",
  "--color-focus-ring": "#a14621",
  "--page-background": "#efe0bd",
  "--surface-background": "#fff8ea",
  "--hero-background": "#e6c992",
  "--cta-background": "#f3e4c2",
  "--font-family-body": "\"Helvetica Neue\", sans-serif",
  "--font-family-heading": "\"Franklin Gothic Medium\", \"Helvetica Neue\", sans-serif",
  "--heading-letter-spacing": "0.03em",
  "--font-size-4": "1.75rem",
  "--font-size-5": "2.25rem",
  "--font-size-6": "3.25rem",
  "--line-height-heading": "0.94",
  "--font-weight-bold": "800",
  "--button-letter-spacing": "0.04em",
  "--button-height": "2.875rem",
  "--radius-sm": "0",
  "--radius-md": "0",
  "--radius-lg": "0",
  "--radius-xl": "0",
  "--border-width-2": "3px",
  "--border-width-3": "4px",
  "--shadow-sm": "2px 2px 0 rgb(0 0 0 / 1)",
  "--shadow-md": "4px 4px 0 rgb(0 0 0 / 1)",
  "--shadow-lg": "6px 6px 0 rgb(0 0 0 / 1)",
  "--button-hover-transform": "none",
});
