import { createThemeDefinition } from "./tokens.js";

export const corporateTheme = createThemeDefinition({
  "--color-scheme": "light",
  "--color-bg": "#f3f1ec",
  "--color-surface": "#ffffff",
  "--color-surface-alt": "#ece7de",
  "--color-text": "#1f1b18",
  "--color-text-muted": "#5f554d",
  "--color-border": "#cbc2b8",
  "--color-primary": "#704c37",
  "--color-primary-contrast": "#ffffff",
  "--color-accent": "#6f7a58",
  "--color-link": "#704c37",
  "--color-link-hover": "#553625",
  "--color-focus-ring": "#8c6248",
  "--page-background": "#f3f1ec",
  "--surface-background": "#ffffff",
  "--hero-background": "#fcfbf8",
  "--cta-background": "#f0ebe2",
  "--font-family-body": "\"IBM Plex Sans\", \"Helvetica Neue\", sans-serif",
  "--font-family-heading": "\"IBM Plex Sans\", \"Helvetica Neue\", sans-serif",
  "--heading-letter-spacing": "-0.01em",
  "--font-size-5": "2rem",
  "--font-size-6": "2.75rem",
  "--line-height-heading": "1.1",
  "--font-weight-semibold": "700",
  "--button-letter-spacing": "0.01em",
  "--space-7": "2.5rem",
  "--container-max": "74rem",
  "--radius-md": "0.375rem",
  "--radius-lg": "0.5rem",
  "--radius-xl": "0.625rem",
  "--shadow-sm": "0 1px 2px rgb(16 24 40 / 0.05)",
  "--shadow-md": "0 3px 10px rgb(16 24 40 / 0.08)",
  "--shadow-lg": "0 8px 24px rgb(16 24 40 / 0.1)",
});
