import { createThemeDefinition } from "./tokens.js";

export const darkSaasTheme = createThemeDefinition(
  {
    "--color-scheme": "dark",
    "--color-bg": "#141110",
    "--color-surface": "#1d1917",
    "--color-surface-alt": "#28221e",
    "--color-text": "#f0ebe4",
    "--color-text-muted": "#b1a79b",
    "--color-border": "#3b332d",
    "--color-primary": "#aa6a45",
    "--color-primary-contrast": "#fff7ef",
    "--color-accent": "#6f7452",
    "--color-link": "#cf9168",
    "--color-link-hover": "#e1a77d",
    "--color-success": "#5d7a60",
    "--color-warning": "#b28853",
    "--color-danger": "#bb6a60",
    "--color-focus-ring": "#a78665",
    "--page-background": "#141110",
    "--surface-background": "#1d1917",
    "--hero-background": "#181513",
    "--cta-background": "#221d19",
    "--font-family-body": "\"Helvetica Neue\", \"Liberation Sans\", sans-serif",
    "--font-family-heading": "\"Helvetica Neue\", \"Liberation Sans\", sans-serif",
    "--heading-letter-spacing": "-0.015em",
    "--line-height-heading": "1.08",
    "--button-letter-spacing": "0.01em",
    "--button-height": "2.5rem",
    "--radius-md": "0.375rem",
    "--radius-lg": "0.5rem",
    "--radius-xl": "0.625rem",
    "--shadow-sm": "0 1px 2px rgb(0 0 0 / 0.18)",
    "--shadow-md": "0 4px 12px rgb(0 0 0 / 0.18)",
    "--shadow-lg": "0 8px 24px rgb(0 0 0 / 0.22)",
    "--button-hover-transform": "none",
  },
);
